# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execution permission
      run : chmod +x gradlew
    - name : Build with Gradle
      run : ./gradlew  build
    -
      name: Build and push 
      #uses: docker/build-push-action@v1
      #with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    repository: mitdosi8919/practicedocker
      #    tag_with_ref: true
      #    tag-_with_sha: true
      #    add_git_labels: true
      #    always_pull: true
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: mitdosi8919/practicedocker
        tag: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
  deploy_to_azure:
      name: deploy to azure
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: azure/actions/login@master
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        #- uses: azure/appservice-actions/webapp-container@master
        #  with:
        #    app-name: "demo"
        #    images: 'https://hub.docker.com/repository/docker/mitdosi8919/practicedocker:main'     
        -
          name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Run docker commands
          run: |
            sudo docker pull mitdosi8919/practicedocker:latest
            sudo docker run -dit -p 80:3010 mitdosi8919/practicedocker:latest
